/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.Profile;
import io.swagger.client.model.SearchRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProfileApi
 */
@Ignore
public class ProfileApiTest {

    private final ProfileApi api = new ProfileApi();
    
    /**
     * Get profile by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProfileTest() throws ApiException {
        String propertyCode = "shasta";
        String id = null;
        Profile response = api.getProfile(propertyCode, id);

        // TODO: test validations
    }
    
    /**
     * Get profiles by date range. Paging is included. Maximum value of returned profiles is 1000
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProfilesTest() throws ApiException {
        SearchRequest searchRequest = null;
        InlineResponse200 response = api.getProfiles(searchRequest);

        // TODO: test validations
    }
    
}
