/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.Rate;
import io.swagger.client.model.SearchRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RateApi
 */
@Ignore
public class RateApiTest {

    private final RateApi api = new RateApi();

    
    /**
     * Get rate by rateCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRateTest() throws ApiException {
        String propertyCode = null;
        String rateCode = null;
        Rate response = api.getRate(propertyCode, rateCode);

        // TODO: test validations
    }
    
    /**
     * Get rates by date range. Paging is included. Maximum value of returned rates is 1000
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRatesTest() throws ApiException {
        SearchRequest searchRequest = null;
        InlineResponse200 response = api.getRates(searchRequest);

        // TODO: test validations
    }
    
}
