/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.SearchRequest;
import io.swagger.client.model.Stay;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StayApi
 */
@Ignore
public class StayApiTest {

    private final StayApi api = new StayApi();

    
    /**
     * Get stays by reservation number
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStaysTest() throws ApiException {
        String propertyCode = null;
        String reservationId = null;
        Stay response = api.getStays(propertyCode, reservationId);

        // TODO: test validations
    }
    
    /**
     * Get stays by date range. Paging is included. Maximum value of returned stays is 1000
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchStaysTest() throws ApiException {
        SearchRequest searchRequest = null;
        InlineResponse200 response = api.searchStays(searchRequest);

        // TODO: test validations
    }
    
}
