package io.swagger.client.api;

import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.Configuration;
import io.swagger.client.auth.ApiKeyAuth;
import io.swagger.client.model.Profile;
import io.swagger.client.model.Reservation;

public class TestingMain {

	public static void main(String[] args) throws ApiException{
		// TODO Auto-generated method stub
        
     // Import classes:
      //import io.swagger.client.ApiClient;
      //import io.swagger.client.ApiException;
      //import io.swagger.client.Configuration;
      //import io.swagger.client.auth.*;
      //import io.swagger.client.api.ReservationsApi;

      ApiClient defaultClient = Configuration.getDefaultApiClient();

      // Configure API key authorization: Bearer
      ApiKeyAuth Bearer = (ApiKeyAuth) defaultClient.getAuthentication("Bearer");
      Bearer.setApiKey("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzaGFzdGEiLCJyZXBvc2l0b3J5QWNjZXNzSWQiOiJzaGFzdGEiLCJleHAiOjE1NDg2MzE5ODB9.ZiV4cQDDFSpyoX6Ch-b_x5TMPoxhDr-pIJQ9Zv9CQt8BwLZSxkWMk0sptUwlYdHl7al2mQuKa5Zvh1hyeVy6bg");
      // Uncomment the following line to set a prefix for the API key, e.g. "Token" (defaults to null)
      //Bearer.setApiKeyPrefix("Token");

      ReservationsApi apiInstance = new ReservationsApi();
      String propertyCode = "SHASTA"; // String | Property code as designated in the PMS
      String id = "14740"; // String | Reservation id generated by the PMS
      try {
          Reservation result = apiInstance.getReservation(propertyCode, id);
          System.out.println(result.getComments().get(0).getComment());
          System.out.println(result);
      } catch (ApiException e) {
          System.err.println("Exception when calling ReservationsApi#getReservation");
          e.printStackTrace();
      }
	}

}
