/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Comment;
import io.swagger.client.model.InventoryBlock;
import io.swagger.client.model.Profile;
import io.swagger.client.model.PropertyId;
import io.swagger.client.model.TimeSpan;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * group block of inventory
 */
@ApiModel(description = "group block of inventory")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-26T23:47:35.032Z")
public class Allotment {
  @SerializedName("propertyId")
  private PropertyId propertyId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("blockName")
  private String blockName = null;

  @SerializedName("dates")
  private TimeSpan dates = null;

  @SerializedName("marketCode")
  private String marketCode = null;

  @SerializedName("sourceCode")
  private String sourceCode = null;

  @SerializedName("channelCode")
  private String channelCode = null;

  @SerializedName("bookingMethod")
  private String bookingMethod = null;

  @SerializedName("billingType")
  private String billingType = null;

  @SerializedName("includesFoodAndBev")
  private Boolean includesFoodAndBev = null;

  @SerializedName("blockType")
  private String blockType = null;

  @SerializedName("comments")
  private List<Comment> comments = null;

  @SerializedName("profiles")
  private List<Profile> profiles = null;

  @SerializedName("inventoryBlocks")
  private List<InventoryBlock> inventoryBlocks = null;

  @SerializedName("repositoryCreated")
  private String repositoryCreated = null;

  @SerializedName("repositoryUpdated")
  private String repositoryUpdated = null;

  public Allotment propertyId(PropertyId propertyId) {
    this.propertyId = propertyId;
    return this;
  }

   /**
   * Get propertyId
   * @return propertyId
  **/
  @ApiModelProperty(value = "")
  public PropertyId getPropertyId() {
    return propertyId;
  }

  public void setPropertyId(PropertyId propertyId) {
    this.propertyId = propertyId;
  }

  public Allotment id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Block code and object id
   * @return id
  **/
  @ApiModelProperty(example = "HOLIDAY2018", value = "Block code and object id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Allotment status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Block status
   * @return status
  **/
  @ApiModelProperty(example = "ACTIVE", value = "Block status")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Allotment blockName(String blockName) {
    this.blockName = blockName;
    return this;
  }

   /**
   * Block name
   * @return blockName
  **/
  @ApiModelProperty(example = "CONFERENCE HOLIDAY 2018", value = "Block name")
  public String getBlockName() {
    return blockName;
  }

  public void setBlockName(String blockName) {
    this.blockName = blockName;
  }

  public Allotment dates(TimeSpan dates) {
    this.dates = dates;
    return this;
  }

   /**
   * Get dates
   * @return dates
  **/
  @ApiModelProperty(value = "")
  public TimeSpan getDates() {
    return dates;
  }

  public void setDates(TimeSpan dates) {
    this.dates = dates;
  }

  public Allotment marketCode(String marketCode) {
    this.marketCode = marketCode;
    return this;
  }

   /**
   * code identifying marketing type for rate
   * @return marketCode
  **/
  @ApiModelProperty(example = "F", value = "code identifying marketing type for rate")
  public String getMarketCode() {
    return marketCode;
  }

  public void setMarketCode(String marketCode) {
    this.marketCode = marketCode;
  }

  public Allotment sourceCode(String sourceCode) {
    this.sourceCode = sourceCode;
    return this;
  }

   /**
   * code identifying source of rate associated to block
   * @return sourceCode
  **/
  @ApiModelProperty(example = "SRC", value = "code identifying source of rate associated to block")
  public String getSourceCode() {
    return sourceCode;
  }

  public void setSourceCode(String sourceCode) {
    this.sourceCode = sourceCode;
  }

  public Allotment channelCode(String channelCode) {
    this.channelCode = channelCode;
    return this;
  }

   /**
   * code identifying booking channel for block
   * @return channelCode
  **/
  @ApiModelProperty(example = "SRC", value = "code identifying booking channel for block")
  public String getChannelCode() {
    return channelCode;
  }

  public void setChannelCode(String channelCode) {
    this.channelCode = channelCode;
  }

  public Allotment bookingMethod(String bookingMethod) {
    this.bookingMethod = bookingMethod;
    return this;
  }

   /**
   * code identifying booking method for block
   * @return bookingMethod
  **/
  @ApiModelProperty(example = "IWEB", value = "code identifying booking method for block")
  public String getBookingMethod() {
    return bookingMethod;
  }

  public void setBookingMethod(String bookingMethod) {
    this.bookingMethod = bookingMethod;
  }

  public Allotment billingType(String billingType) {
    this.billingType = billingType;
    return this;
  }

   /**
   * used to indicate if charges should be billed to master account
   * @return billingType
  **/
  @ApiModelProperty(value = "used to indicate if charges should be billed to master account")
  public String getBillingType() {
    return billingType;
  }

  public void setBillingType(String billingType) {
    this.billingType = billingType;
  }

  public Allotment includesFoodAndBev(Boolean includesFoodAndBev) {
    this.includesFoodAndBev = includesFoodAndBev;
    return this;
  }

   /**
   * used to indicate whether food and drinks should be charged to master account
   * @return includesFoodAndBev
  **/
  @ApiModelProperty(example = "true", value = "used to indicate whether food and drinks should be charged to master account")
  public Boolean isIncludesFoodAndBev() {
    return includesFoodAndBev;
  }

  public void setIncludesFoodAndBev(Boolean includesFoodAndBev) {
    this.includesFoodAndBev = includesFoodAndBev;
  }

  public Allotment blockType(String blockType) {
    this.blockType = blockType;
    return this;
  }

   /**
   * type of block
   * @return blockType
  **/
  @ApiModelProperty(example = "ELASTIC", value = "type of block")
  public String getBlockType() {
    return blockType;
  }

  public void setBlockType(String blockType) {
    this.blockType = blockType;
  }

  public Allotment comments(List<Comment> comments) {
    this.comments = comments;
    return this;
  }

  public Allotment addCommentsItem(Comment commentsItem) {
    if (this.comments == null) {
      this.comments = new ArrayList<Comment>();
    }
    this.comments.add(commentsItem);
    return this;
  }

   /**
   * free text comments associated to block
   * @return comments
  **/
  @ApiModelProperty(value = "free text comments associated to block")
  public List<Comment> getComments() {
    return comments;
  }

  public void setComments(List<Comment> comments) {
    this.comments = comments;
  }

  public Allotment profiles(List<Profile> profiles) {
    this.profiles = profiles;
    return this;
  }

  public Allotment addProfilesItem(Profile profilesItem) {
    if (this.profiles == null) {
      this.profiles = new ArrayList<Profile>();
    }
    this.profiles.add(profilesItem);
    return this;
  }

   /**
   * Get profiles
   * @return profiles
  **/
  @ApiModelProperty(value = "")
  public List<Profile> getProfiles() {
    return profiles;
  }

  public void setProfiles(List<Profile> profiles) {
    this.profiles = profiles;
  }

  public Allotment inventoryBlocks(List<InventoryBlock> inventoryBlocks) {
    this.inventoryBlocks = inventoryBlocks;
    return this;
  }

  public Allotment addInventoryBlocksItem(InventoryBlock inventoryBlocksItem) {
    if (this.inventoryBlocks == null) {
      this.inventoryBlocks = new ArrayList<InventoryBlock>();
    }
    this.inventoryBlocks.add(inventoryBlocksItem);
    return this;
  }

   /**
   * Get inventoryBlocks
   * @return inventoryBlocks
  **/
  @ApiModelProperty(value = "")
  public List<InventoryBlock> getInventoryBlocks() {
    return inventoryBlocks;
  }

  public void setInventoryBlocks(List<InventoryBlock> inventoryBlocks) {
    this.inventoryBlocks = inventoryBlocks;
  }

  public Allotment repositoryCreated(String repositoryCreated) {
    this.repositoryCreated = repositoryCreated;
    return this;
  }

   /**
   * repository create date in YYYY-MM-DDThh:mm:ss.sss format
   * @return repositoryCreated
  **/
  @ApiModelProperty(example = "2018-06-01T15:34:54.000", value = "repository create date in YYYY-MM-DDThh:mm:ss.sss format")
  public String getRepositoryCreated() {
    return repositoryCreated;
  }

  public void setRepositoryCreated(String repositoryCreated) {
    this.repositoryCreated = repositoryCreated;
  }

  public Allotment repositoryUpdated(String repositoryUpdated) {
    this.repositoryUpdated = repositoryUpdated;
    return this;
  }

   /**
   * repository update date in YYYY-MM-DDThh:mm:ss.sss format
   * @return repositoryUpdated
  **/
  @ApiModelProperty(example = "2018-06-01T15:34:54.000", value = "repository update date in YYYY-MM-DDThh:mm:ss.sss format")
  public String getRepositoryUpdated() {
    return repositoryUpdated;
  }

  public void setRepositoryUpdated(String repositoryUpdated) {
    this.repositoryUpdated = repositoryUpdated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Allotment allotment = (Allotment) o;
    return Objects.equals(this.propertyId, allotment.propertyId) &&
        Objects.equals(this.id, allotment.id) &&
        Objects.equals(this.status, allotment.status) &&
        Objects.equals(this.blockName, allotment.blockName) &&
        Objects.equals(this.dates, allotment.dates) &&
        Objects.equals(this.marketCode, allotment.marketCode) &&
        Objects.equals(this.sourceCode, allotment.sourceCode) &&
        Objects.equals(this.channelCode, allotment.channelCode) &&
        Objects.equals(this.bookingMethod, allotment.bookingMethod) &&
        Objects.equals(this.billingType, allotment.billingType) &&
        Objects.equals(this.includesFoodAndBev, allotment.includesFoodAndBev) &&
        Objects.equals(this.blockType, allotment.blockType) &&
        Objects.equals(this.comments, allotment.comments) &&
        Objects.equals(this.profiles, allotment.profiles) &&
        Objects.equals(this.inventoryBlocks, allotment.inventoryBlocks) &&
        Objects.equals(this.repositoryCreated, allotment.repositoryCreated) &&
        Objects.equals(this.repositoryUpdated, allotment.repositoryUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyId, id, status, blockName, dates, marketCode, sourceCode, channelCode, bookingMethod, billingType, includesFoodAndBev, blockType, comments, profiles, inventoryBlocks, repositoryCreated, repositoryUpdated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Allotment {\n");
    
    sb.append("    propertyId: ").append(toIndentedString(propertyId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    blockName: ").append(toIndentedString(blockName)).append("\n");
    sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
    sb.append("    marketCode: ").append(toIndentedString(marketCode)).append("\n");
    sb.append("    sourceCode: ").append(toIndentedString(sourceCode)).append("\n");
    sb.append("    channelCode: ").append(toIndentedString(channelCode)).append("\n");
    sb.append("    bookingMethod: ").append(toIndentedString(bookingMethod)).append("\n");
    sb.append("    billingType: ").append(toIndentedString(billingType)).append("\n");
    sb.append("    includesFoodAndBev: ").append(toIndentedString(includesFoodAndBev)).append("\n");
    sb.append("    blockType: ").append(toIndentedString(blockType)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    profiles: ").append(toIndentedString(profiles)).append("\n");
    sb.append("    inventoryBlocks: ").append(toIndentedString(inventoryBlocks)).append("\n");
    sb.append("    repositoryCreated: ").append(toIndentedString(repositoryCreated)).append("\n");
    sb.append("    repositoryUpdated: ").append(toIndentedString(repositoryUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

