/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BlockRate;
import io.swagger.client.model.TimeSpan;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * inventory block detail for allotment
 */
@ApiModel(description = "inventory block detail for allotment")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-26T23:47:35.032Z")
public class InventoryBlock {
  @SerializedName("roomType")
  private String roomType = null;

  @SerializedName("rateCode")
  private String rateCode = null;

  @SerializedName("dates")
  private TimeSpan dates = null;

  @SerializedName("cutoffDate")
  private String cutoffDate = null;

  @SerializedName("numberToBlock")
  private Integer numberToBlock = null;

  @SerializedName("numberSold")
  private Integer numberSold = null;

  @SerializedName("compRoomsNumber")
  private Integer compRoomsNumber = null;

  @SerializedName("currencyCode")
  private String currencyCode = null;

  @SerializedName("rates")
  private List<BlockRate> rates = null;

  public InventoryBlock roomType(String roomType) {
    this.roomType = roomType;
    return this;
  }

   /**
   * Room type
   * @return roomType
  **/
  @ApiModelProperty(example = "KING", value = "Room type")
  public String getRoomType() {
    return roomType;
  }

  public void setRoomType(String roomType) {
    this.roomType = roomType;
  }

  public InventoryBlock rateCode(String rateCode) {
    this.rateCode = rateCode;
    return this;
  }

   /**
   * code identifying rate for block
   * @return rateCode
  **/
  @ApiModelProperty(example = "AAA", value = "code identifying rate for block")
  public String getRateCode() {
    return rateCode;
  }

  public void setRateCode(String rateCode) {
    this.rateCode = rateCode;
  }

  public InventoryBlock dates(TimeSpan dates) {
    this.dates = dates;
    return this;
  }

   /**
   * Get dates
   * @return dates
  **/
  @ApiModelProperty(value = "")
  public TimeSpan getDates() {
    return dates;
  }

  public void setDates(TimeSpan dates) {
    this.dates = dates;
  }

  public InventoryBlock cutoffDate(String cutoffDate) {
    this.cutoffDate = cutoffDate;
    return this;
  }

   /**
   * used to determine when the inventory block is released back into house inventory
   * @return cutoffDate
  **/
  @ApiModelProperty(example = "2018-12-01", value = "used to determine when the inventory block is released back into house inventory")
  public String getCutoffDate() {
    return cutoffDate;
  }

  public void setCutoffDate(String cutoffDate) {
    this.cutoffDate = cutoffDate;
  }

  public InventoryBlock numberToBlock(Integer numberToBlock) {
    this.numberToBlock = numberToBlock;
    return this;
  }

   /**
   * number of rooms for this block per day per room type
   * @return numberToBlock
  **/
  @ApiModelProperty(example = "2", value = "number of rooms for this block per day per room type")
  public Integer getNumberToBlock() {
    return numberToBlock;
  }

  public void setNumberToBlock(Integer numberToBlock) {
    this.numberToBlock = numberToBlock;
  }

  public InventoryBlock numberSold(Integer numberSold) {
    this.numberSold = numberSold;
    return this;
  }

   /**
   * number of rooms sold in block
   * @return numberSold
  **/
  @ApiModelProperty(example = "5", value = "number of rooms sold in block")
  public Integer getNumberSold() {
    return numberSold;
  }

  public void setNumberSold(Integer numberSold) {
    this.numberSold = numberSold;
  }

  public InventoryBlock compRoomsNumber(Integer compRoomsNumber) {
    this.compRoomsNumber = compRoomsNumber;
    return this;
  }

   /**
   * number of comp rooms available in block
   * @return compRoomsNumber
  **/
  @ApiModelProperty(example = "0", value = "number of comp rooms available in block")
  public Integer getCompRoomsNumber() {
    return compRoomsNumber;
  }

  public void setCompRoomsNumber(Integer compRoomsNumber) {
    this.compRoomsNumber = compRoomsNumber;
  }

  public InventoryBlock currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * code identifying type of currency associated to rate
   * @return currencyCode
  **/
  @ApiModelProperty(example = "USD", value = "code identifying type of currency associated to rate")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public InventoryBlock rates(List<BlockRate> rates) {
    this.rates = rates;
    return this;
  }

  public InventoryBlock addRatesItem(BlockRate ratesItem) {
    if (this.rates == null) {
      this.rates = new ArrayList<BlockRate>();
    }
    this.rates.add(ratesItem);
    return this;
  }

   /**
   * rate and occupancy detail for room type in block
   * @return rates
  **/
  @ApiModelProperty(value = "rate and occupancy detail for room type in block")
  public List<BlockRate> getRates() {
    return rates;
  }

  public void setRates(List<BlockRate> rates) {
    this.rates = rates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventoryBlock inventoryBlock = (InventoryBlock) o;
    return Objects.equals(this.roomType, inventoryBlock.roomType) &&
        Objects.equals(this.rateCode, inventoryBlock.rateCode) &&
        Objects.equals(this.dates, inventoryBlock.dates) &&
        Objects.equals(this.cutoffDate, inventoryBlock.cutoffDate) &&
        Objects.equals(this.numberToBlock, inventoryBlock.numberToBlock) &&
        Objects.equals(this.numberSold, inventoryBlock.numberSold) &&
        Objects.equals(this.compRoomsNumber, inventoryBlock.compRoomsNumber) &&
        Objects.equals(this.currencyCode, inventoryBlock.currencyCode) &&
        Objects.equals(this.rates, inventoryBlock.rates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roomType, rateCode, dates, cutoffDate, numberToBlock, numberSold, compRoomsNumber, currencyCode, rates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryBlock {\n");
    
    sb.append("    roomType: ").append(toIndentedString(roomType)).append("\n");
    sb.append("    rateCode: ").append(toIndentedString(rateCode)).append("\n");
    sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
    sb.append("    cutoffDate: ").append(toIndentedString(cutoffDate)).append("\n");
    sb.append("    numberToBlock: ").append(toIndentedString(numberToBlock)).append("\n");
    sb.append("    numberSold: ").append(toIndentedString(numberSold)).append("\n");
    sb.append("    compRoomsNumber: ").append(toIndentedString(compRoomsNumber)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    rates: ").append(toIndentedString(rates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

