/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PropertyId;
import io.swagger.client.model.RateDetail;
import io.swagger.client.model.TimeSpan;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Rate
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-26T23:47:35.032Z")
public class Rate {
  @SerializedName("propertyId")
  private PropertyId propertyId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("sellDates")
  private TimeSpan sellDates = null;

  @SerializedName("category")
  private String category = null;

  @SerializedName("marketCode")
  private String marketCode = null;

  @SerializedName("sourceCode")
  private String sourceCode = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("yieldStatus")
  private String yieldStatus = null;

  @SerializedName("details")
  private List<RateDetail> details = null;

  @SerializedName("repositoryCreated")
  private String repositoryCreated = null;

  @SerializedName("repositoryUpdated")
  private String repositoryUpdated = null;

  public Rate propertyId(PropertyId propertyId) {
    this.propertyId = propertyId;
    return this;
  }

   /**
   * Get propertyId
   * @return propertyId
  **/
  @ApiModelProperty(value = "")
  public PropertyId getPropertyId() {
    return propertyId;
  }

  public void setPropertyId(PropertyId propertyId) {
    this.propertyId = propertyId;
  }

  public Rate id(String id) {
    this.id = id;
    return this;
  }

   /**
   * header rate code
   * @return id
  **/
  @ApiModelProperty(example = "BAR", value = "header rate code")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Rate sellDates(TimeSpan sellDates) {
    this.sellDates = sellDates;
    return this;
  }

   /**
   * Get sellDates
   * @return sellDates
  **/
  @ApiModelProperty(value = "")
  public TimeSpan getSellDates() {
    return sellDates;
  }

  public void setSellDates(TimeSpan sellDates) {
    this.sellDates = sellDates;
  }

  public Rate category(String category) {
    this.category = category;
    return this;
  }

   /**
   * rate category
   * @return category
  **/
  @ApiModelProperty(example = "STD", value = "rate category")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public Rate marketCode(String marketCode) {
    this.marketCode = marketCode;
    return this;
  }

   /**
   * rate marketing code
   * @return marketCode
  **/
  @ApiModelProperty(example = "DM", value = "rate marketing code")
  public String getMarketCode() {
    return marketCode;
  }

  public void setMarketCode(String marketCode) {
    this.marketCode = marketCode;
  }

  public Rate sourceCode(String sourceCode) {
    this.sourceCode = sourceCode;
    return this;
  }

   /**
   * rate source code
   * @return sourceCode
  **/
  @ApiModelProperty(example = "SRC", value = "rate source code")
  public String getSourceCode() {
    return sourceCode;
  }

  public void setSourceCode(String sourceCode) {
    this.sourceCode = sourceCode;
  }

  public Rate status(String status) {
    this.status = status;
    return this;
  }

   /**
   * active status of rate
   * @return status
  **/
  @ApiModelProperty(example = "ACTIVE", value = "active status of rate")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Rate yieldStatus(String yieldStatus) {
    this.yieldStatus = yieldStatus;
    return this;
  }

   /**
   * is rate yieldable
   * @return yieldStatus
  **/
  @ApiModelProperty(example = "FULLY", value = "is rate yieldable")
  public String getYieldStatus() {
    return yieldStatus;
  }

  public void setYieldStatus(String yieldStatus) {
    this.yieldStatus = yieldStatus;
  }

  public Rate details(List<RateDetail> details) {
    this.details = details;
    return this;
  }

  public Rate addDetailsItem(RateDetail detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<RateDetail>();
    }
    this.details.add(detailsItem);
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @ApiModelProperty(value = "")
  public List<RateDetail> getDetails() {
    return details;
  }

  public void setDetails(List<RateDetail> details) {
    this.details = details;
  }

  public Rate repositoryCreated(String repositoryCreated) {
    this.repositoryCreated = repositoryCreated;
    return this;
  }

   /**
   * repository create date in YYYY-MM-DDThh:mm:ss.sss format
   * @return repositoryCreated
  **/
  @ApiModelProperty(example = "2018-06-01T15:34:54.000", value = "repository create date in YYYY-MM-DDThh:mm:ss.sss format")
  public String getRepositoryCreated() {
    return repositoryCreated;
  }

  public void setRepositoryCreated(String repositoryCreated) {
    this.repositoryCreated = repositoryCreated;
  }

  public Rate repositoryUpdated(String repositoryUpdated) {
    this.repositoryUpdated = repositoryUpdated;
    return this;
  }

   /**
   * repository update date in YYYY-MM-DDThh:mm:ss.sss format
   * @return repositoryUpdated
  **/
  @ApiModelProperty(example = "2018-06-01T15:34:54.000", value = "repository update date in YYYY-MM-DDThh:mm:ss.sss format")
  public String getRepositoryUpdated() {
    return repositoryUpdated;
  }

  public void setRepositoryUpdated(String repositoryUpdated) {
    this.repositoryUpdated = repositoryUpdated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rate rate = (Rate) o;
    return Objects.equals(this.propertyId, rate.propertyId) &&
        Objects.equals(this.id, rate.id) &&
        Objects.equals(this.sellDates, rate.sellDates) &&
        Objects.equals(this.category, rate.category) &&
        Objects.equals(this.marketCode, rate.marketCode) &&
        Objects.equals(this.sourceCode, rate.sourceCode) &&
        Objects.equals(this.status, rate.status) &&
        Objects.equals(this.yieldStatus, rate.yieldStatus) &&
        Objects.equals(this.details, rate.details) &&
        Objects.equals(this.repositoryCreated, rate.repositoryCreated) &&
        Objects.equals(this.repositoryUpdated, rate.repositoryUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyId, id, sellDates, category, marketCode, sourceCode, status, yieldStatus, details, repositoryCreated, repositoryUpdated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rate {\n");
    
    sb.append("    propertyId: ").append(toIndentedString(propertyId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sellDates: ").append(toIndentedString(sellDates)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    marketCode: ").append(toIndentedString(marketCode)).append("\n");
    sb.append("    sourceCode: ").append(toIndentedString(sourceCode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    yieldStatus: ").append(toIndentedString(yieldStatus)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    repositoryCreated: ").append(toIndentedString(repositoryCreated)).append("\n");
    sb.append("    repositoryUpdated: ").append(toIndentedString(repositoryUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

