/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RateInfo;
import io.swagger.client.model.TimeSpan;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * RateDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-26T23:47:35.032Z")
public class RateDetail {
  @SerializedName("dates")
  private TimeSpan dates = null;

  @SerializedName("rateCode")
  private String rateCode = null;

  @SerializedName("marketCode")
  private String marketCode = null;

  @SerializedName("sourceCode")
  private String sourceCode = null;

  @SerializedName("packages")
  private String packages = null;

  @SerializedName("roomTypes")
  private List<String> roomTypes = null;

  @SerializedName("daysOfWeek")
  private List<String> daysOfWeek = null;

  @SerializedName("rates")
  private List<RateInfo> rates = null;

  public RateDetail dates(TimeSpan dates) {
    this.dates = dates;
    return this;
  }

   /**
   * Get dates
   * @return dates
  **/
  @ApiModelProperty(value = "")
  public TimeSpan getDates() {
    return dates;
  }

  public void setDates(TimeSpan dates) {
    this.dates = dates;
  }

  public RateDetail rateCode(String rateCode) {
    this.rateCode = rateCode;
    return this;
  }

   /**
   * detail rate code
   * @return rateCode
  **/
  @ApiModelProperty(example = "RACK", value = "detail rate code")
  public String getRateCode() {
    return rateCode;
  }

  public void setRateCode(String rateCode) {
    this.rateCode = rateCode;
  }

  public RateDetail marketCode(String marketCode) {
    this.marketCode = marketCode;
    return this;
  }

   /**
   * rate marketing code
   * @return marketCode
  **/
  @ApiModelProperty(example = "DM", value = "rate marketing code")
  public String getMarketCode() {
    return marketCode;
  }

  public void setMarketCode(String marketCode) {
    this.marketCode = marketCode;
  }

  public RateDetail sourceCode(String sourceCode) {
    this.sourceCode = sourceCode;
    return this;
  }

   /**
   * rate source code
   * @return sourceCode
  **/
  @ApiModelProperty(example = "SRC", value = "rate source code")
  public String getSourceCode() {
    return sourceCode;
  }

  public void setSourceCode(String sourceCode) {
    this.sourceCode = sourceCode;
  }

  public RateDetail packages(String packages) {
    this.packages = packages;
    return this;
  }

   /**
   * packages included in rate
   * @return packages
  **/
  @ApiModelProperty(example = "ACTIVE", value = "packages included in rate")
  public String getPackages() {
    return packages;
  }

  public void setPackages(String packages) {
    this.packages = packages;
  }

  public RateDetail roomTypes(List<String> roomTypes) {
    this.roomTypes = roomTypes;
    return this;
  }

  public RateDetail addRoomTypesItem(String roomTypesItem) {
    if (this.roomTypes == null) {
      this.roomTypes = new ArrayList<String>();
    }
    this.roomTypes.add(roomTypesItem);
    return this;
  }

   /**
   * valid room types for rate
   * @return roomTypes
  **/
  @ApiModelProperty(example = "\"K1,Q1\"", value = "valid room types for rate")
  public List<String> getRoomTypes() {
    return roomTypes;
  }

  public void setRoomTypes(List<String> roomTypes) {
    this.roomTypes = roomTypes;
  }

  public RateDetail daysOfWeek(List<String> daysOfWeek) {
    this.daysOfWeek = daysOfWeek;
    return this;
  }

  public RateDetail addDaysOfWeekItem(String daysOfWeekItem) {
    if (this.daysOfWeek == null) {
      this.daysOfWeek = new ArrayList<String>();
    }
    this.daysOfWeek.add(daysOfWeekItem);
    return this;
  }

   /**
   * Days of the week for which the rate is valid
   * @return daysOfWeek
  **/
  @ApiModelProperty(example = "\"FRIDAY,SATURDAY,SUNDAY\"", value = "Days of the week for which the rate is valid")
  public List<String> getDaysOfWeek() {
    return daysOfWeek;
  }

  public void setDaysOfWeek(List<String> daysOfWeek) {
    this.daysOfWeek = daysOfWeek;
  }

  public RateDetail rates(List<RateInfo> rates) {
    this.rates = rates;
    return this;
  }

  public RateDetail addRatesItem(RateInfo ratesItem) {
    if (this.rates == null) {
      this.rates = new ArrayList<RateInfo>();
    }
    this.rates.add(ratesItem);
    return this;
  }

   /**
   * Rate amounts by number of guests and guest type
   * @return rates
  **/
  @ApiModelProperty(value = "Rate amounts by number of guests and guest type")
  public List<RateInfo> getRates() {
    return rates;
  }

  public void setRates(List<RateInfo> rates) {
    this.rates = rates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RateDetail rateDetail = (RateDetail) o;
    return Objects.equals(this.dates, rateDetail.dates) &&
        Objects.equals(this.rateCode, rateDetail.rateCode) &&
        Objects.equals(this.marketCode, rateDetail.marketCode) &&
        Objects.equals(this.sourceCode, rateDetail.sourceCode) &&
        Objects.equals(this.packages, rateDetail.packages) &&
        Objects.equals(this.roomTypes, rateDetail.roomTypes) &&
        Objects.equals(this.daysOfWeek, rateDetail.daysOfWeek) &&
        Objects.equals(this.rates, rateDetail.rates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dates, rateCode, marketCode, sourceCode, packages, roomTypes, daysOfWeek, rates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RateDetail {\n");
    
    sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
    sb.append("    rateCode: ").append(toIndentedString(rateCode)).append("\n");
    sb.append("    marketCode: ").append(toIndentedString(marketCode)).append("\n");
    sb.append("    sourceCode: ").append(toIndentedString(sourceCode)).append("\n");
    sb.append("    packages: ").append(toIndentedString(packages)).append("\n");
    sb.append("    roomTypes: ").append(toIndentedString(roomTypes)).append("\n");
    sb.append("    daysOfWeek: ").append(toIndentedString(daysOfWeek)).append("\n");
    sb.append("    rates: ").append(toIndentedString(rates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

