/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Comment;
import io.swagger.client.model.Guest;
import io.swagger.client.model.Profile;
import io.swagger.client.model.PropertyId;
import io.swagger.client.model.RoomStay;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Reservation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-26T23:47:35.032Z")
public class Reservation {
  @SerializedName("propertyId")
  private PropertyId propertyId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("bookingConfirmationId")
  private String bookingConfirmationId = null;

  @SerializedName("arrivalDate")
  private String arrivalDate = null;

  @SerializedName("arrivalTime")
  private String arrivalTime = null;

  @SerializedName("departureDate")
  private String departureDate = null;

  @SerializedName("creator")
  private String creator = null;

  @SerializedName("createdDate")
  private String createdDate = null;

  @SerializedName("cancelledDate")
  private String cancelledDate = null;

  @SerializedName("cancellationNumber")
  private String cancellationNumber = null;

  @SerializedName("adults")
  private Integer adults = null;

  @SerializedName("children")
  private Integer children = null;

  /**
   * current status of reservation
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    REQUESTED("REQUESTED"),
    
    RESERVED("RESERVED"),
    
    IN_HOUSE("IN_HOUSE"),
    
    CANCELLED("CANCELLED"),
    
    CHECKED_OUT("CHECKED_OUT"),
    
    NO_SHOW("NO_SHOW"),
    
    WAIT_LIST("WAIT_LIST"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("guests")
  private List<Guest> guests = null;

  @SerializedName("profiles")
  private List<Profile> profiles = null;

  @SerializedName("roomStays")
  private List<RoomStay> roomStays = null;

  @SerializedName("comments")
  private List<Comment> comments = null;

  @SerializedName("repositoryCreated")
  private String repositoryCreated = null;

  @SerializedName("repositoryUpdated")
  private String repositoryUpdated = null;

  public Reservation propertyId(PropertyId propertyId) {
    this.propertyId = propertyId;
    return this;
  }

   /**
   * Get propertyId
   * @return propertyId
  **/
  @ApiModelProperty(value = "")
  public PropertyId getPropertyId() {
    return propertyId;
  }

  public void setPropertyId(PropertyId propertyId) {
    this.propertyId = propertyId;
  }

  public Reservation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * reservation identifier and object key
   * @return id
  **/
  @ApiModelProperty(example = "542154", value = "reservation identifier and object key")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Reservation bookingConfirmationId(String bookingConfirmationId) {
    this.bookingConfirmationId = bookingConfirmationId;
    return this;
  }

   /**
   * unique confirmation id within given hotel
   * @return bookingConfirmationId
  **/
  @ApiModelProperty(example = "L7RR1A", value = "unique confirmation id within given hotel")
  public String getBookingConfirmationId() {
    return bookingConfirmationId;
  }

  public void setBookingConfirmationId(String bookingConfirmationId) {
    this.bookingConfirmationId = bookingConfirmationId;
  }

  public Reservation arrivalDate(String arrivalDate) {
    this.arrivalDate = arrivalDate;
    return this;
  }

   /**
   * check-in date, in YYYY-MM-DD format
   * @return arrivalDate
  **/
  @ApiModelProperty(example = "2018-08-23", value = "check-in date, in YYYY-MM-DD format")
  public String getArrivalDate() {
    return arrivalDate;
  }

  public void setArrivalDate(String arrivalDate) {
    this.arrivalDate = arrivalDate;
  }

  public Reservation arrivalTime(String arrivalTime) {
    this.arrivalTime = arrivalTime;
    return this;
  }

   /**
   * estimated check-in time
   * @return arrivalTime
  **/
  @ApiModelProperty(example = "5:00PM", value = "estimated check-in time")
  public String getArrivalTime() {
    return arrivalTime;
  }

  public void setArrivalTime(String arrivalTime) {
    this.arrivalTime = arrivalTime;
  }

  public Reservation departureDate(String departureDate) {
    this.departureDate = departureDate;
    return this;
  }

   /**
   * check-out date, in YYYY-MM-DD format
   * @return departureDate
  **/
  @ApiModelProperty(example = "2018-08-25", value = "check-out date, in YYYY-MM-DD format")
  public String getDepartureDate() {
    return departureDate;
  }

  public void setDepartureDate(String departureDate) {
    this.departureDate = departureDate;
  }

  public Reservation creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * user or interface who created the reservation
   * @return creator
  **/
  @ApiModelProperty(example = "GARCIA", value = "user or interface who created the reservation")
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public Reservation createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * read-only reservation create date in hotel, in YYYY-MM-DDThh:mm:ss.sss format
   * @return createdDate
  **/
  @ApiModelProperty(example = "2018-06-01T15:34:54.000", value = "read-only reservation create date in hotel, in YYYY-MM-DDThh:mm:ss.sss format")
  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }

  public Reservation cancelledDate(String cancelledDate) {
    this.cancelledDate = cancelledDate;
    return this;
  }

   /**
   * Reservation cancellation date in hotel, in YYYY-MM-DDThh:mm:ss.sss format
   * @return cancelledDate
  **/
  @ApiModelProperty(example = "2018-06-01T15:34:54.000", value = "Reservation cancellation date in hotel, in YYYY-MM-DDThh:mm:ss.sss format")
  public String getCancelledDate() {
    return cancelledDate;
  }

  public void setCancelledDate(String cancelledDate) {
    this.cancelledDate = cancelledDate;
  }

  public Reservation cancellationNumber(String cancellationNumber) {
    this.cancellationNumber = cancellationNumber;
    return this;
  }

   /**
   * cancellation number for reservation. may be supplied externally or returned from pms
   * @return cancellationNumber
  **/
  @ApiModelProperty(example = "CXL12345", value = "cancellation number for reservation. may be supplied externally or returned from pms")
  public String getCancellationNumber() {
    return cancellationNumber;
  }

  public void setCancellationNumber(String cancellationNumber) {
    this.cancellationNumber = cancellationNumber;
  }

  public Reservation adults(Integer adults) {
    this.adults = adults;
    return this;
  }

   /**
   * Get adults
   * @return adults
  **/
  @ApiModelProperty(example = "2", value = "")
  public Integer getAdults() {
    return adults;
  }

  public void setAdults(Integer adults) {
    this.adults = adults;
  }

  public Reservation children(Integer children) {
    this.children = children;
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @ApiModelProperty(example = "1", value = "")
  public Integer getChildren() {
    return children;
  }

  public void setChildren(Integer children) {
    this.children = children;
  }

  public Reservation status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * current status of reservation
   * @return status
  **/
  @ApiModelProperty(example = "RESERVED", value = "current status of reservation")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public Reservation guests(List<Guest> guests) {
    this.guests = guests;
    return this;
  }

  public Reservation addGuestsItem(Guest guestsItem) {
    if (this.guests == null) {
      this.guests = new ArrayList<Guest>();
    }
    this.guests.add(guestsItem);
    return this;
  }

   /**
   * Get guests
   * @return guests
  **/
  @ApiModelProperty(value = "")
  public List<Guest> getGuests() {
    return guests;
  }

  public void setGuests(List<Guest> guests) {
    this.guests = guests;
  }

  public Reservation profiles(List<Profile> profiles) {
    this.profiles = profiles;
    return this;
  }

  public Reservation addProfilesItem(Profile profilesItem) {
    if (this.profiles == null) {
      this.profiles = new ArrayList<Profile>();
    }
    this.profiles.add(profilesItem);
    return this;
  }

   /**
   * Get profiles
   * @return profiles
  **/
  @ApiModelProperty(value = "")
  public List<Profile> getProfiles() {
    return profiles;
  }

  public void setProfiles(List<Profile> profiles) {
    this.profiles = profiles;
  }

  public Reservation roomStays(List<RoomStay> roomStays) {
    this.roomStays = roomStays;
    return this;
  }

  public Reservation addRoomStaysItem(RoomStay roomStaysItem) {
    if (this.roomStays == null) {
      this.roomStays = new ArrayList<RoomStay>();
    }
    this.roomStays.add(roomStaysItem);
    return this;
  }

   /**
   * Get roomStays
   * @return roomStays
  **/
  @ApiModelProperty(value = "")
  public List<RoomStay> getRoomStays() {
    return roomStays;
  }

  public void setRoomStays(List<RoomStay> roomStays) {
    this.roomStays = roomStays;
  }

  public Reservation comments(List<Comment> comments) {
    this.comments = comments;
    return this;
  }

  public Reservation addCommentsItem(Comment commentsItem) {
    if (this.comments == null) {
      this.comments = new ArrayList<Comment>();
    }
    this.comments.add(commentsItem);
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @ApiModelProperty(value = "")
  public List<Comment> getComments() {
    return comments;
  }

  public void setComments(List<Comment> comments) {
    this.comments = comments;
  }

  public Reservation repositoryCreated(String repositoryCreated) {
    this.repositoryCreated = repositoryCreated;
    return this;
  }

   /**
   * repository create date in YYYY-MM-DDThh:mm:ss.sss format
   * @return repositoryCreated
  **/
  @ApiModelProperty(example = "2018-06-01T15:34:54.000", value = "repository create date in YYYY-MM-DDThh:mm:ss.sss format")
  public String getRepositoryCreated() {
    return repositoryCreated;
  }

  public void setRepositoryCreated(String repositoryCreated) {
    this.repositoryCreated = repositoryCreated;
  }

  public Reservation repositoryUpdated(String repositoryUpdated) {
    this.repositoryUpdated = repositoryUpdated;
    return this;
  }

   /**
   * repository update date in YYYY-MM-DDThh:mm:ss.sss format
   * @return repositoryUpdated
  **/
  @ApiModelProperty(example = "2018-06-01T15:34:54.000", value = "repository update date in YYYY-MM-DDThh:mm:ss.sss format")
  public String getRepositoryUpdated() {
    return repositoryUpdated;
  }

  public void setRepositoryUpdated(String repositoryUpdated) {
    this.repositoryUpdated = repositoryUpdated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Reservation reservation = (Reservation) o;
    return Objects.equals(this.propertyId, reservation.propertyId) &&
        Objects.equals(this.id, reservation.id) &&
        Objects.equals(this.bookingConfirmationId, reservation.bookingConfirmationId) &&
        Objects.equals(this.arrivalDate, reservation.arrivalDate) &&
        Objects.equals(this.arrivalTime, reservation.arrivalTime) &&
        Objects.equals(this.departureDate, reservation.departureDate) &&
        Objects.equals(this.creator, reservation.creator) &&
        Objects.equals(this.createdDate, reservation.createdDate) &&
        Objects.equals(this.cancelledDate, reservation.cancelledDate) &&
        Objects.equals(this.cancellationNumber, reservation.cancellationNumber) &&
        Objects.equals(this.adults, reservation.adults) &&
        Objects.equals(this.children, reservation.children) &&
        Objects.equals(this.status, reservation.status) &&
        Objects.equals(this.guests, reservation.guests) &&
        Objects.equals(this.profiles, reservation.profiles) &&
        Objects.equals(this.roomStays, reservation.roomStays) &&
        Objects.equals(this.comments, reservation.comments) &&
        Objects.equals(this.repositoryCreated, reservation.repositoryCreated) &&
        Objects.equals(this.repositoryUpdated, reservation.repositoryUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyId, id, bookingConfirmationId, arrivalDate, arrivalTime, departureDate, creator, createdDate, cancelledDate, cancellationNumber, adults, children, status, guests, profiles, roomStays, comments, repositoryCreated, repositoryUpdated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Reservation {\n");
    
    sb.append("    propertyId: ").append(toIndentedString(propertyId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    bookingConfirmationId: ").append(toIndentedString(bookingConfirmationId)).append("\n");
    sb.append("    arrivalDate: ").append(toIndentedString(arrivalDate)).append("\n");
    sb.append("    arrivalTime: ").append(toIndentedString(arrivalTime)).append("\n");
    sb.append("    departureDate: ").append(toIndentedString(departureDate)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    cancelledDate: ").append(toIndentedString(cancelledDate)).append("\n");
    sb.append("    cancellationNumber: ").append(toIndentedString(cancellationNumber)).append("\n");
    sb.append("    adults: ").append(toIndentedString(adults)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    guests: ").append(toIndentedString(guests)).append("\n");
    sb.append("    profiles: ").append(toIndentedString(profiles)).append("\n");
    sb.append("    roomStays: ").append(toIndentedString(roomStays)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    repositoryCreated: ").append(toIndentedString(repositoryCreated)).append("\n");
    sb.append("    repositoryUpdated: ").append(toIndentedString(repositoryUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

