/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * details related to revenue
 */
@ApiModel(description = "details related to revenue")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-26T23:47:35.032Z")
public class Revenue {
  @SerializedName("type")
  private String type = null;

  @SerializedName("currencyCode")
  private String currencyCode = null;

  @SerializedName("amount")
  private BigDecimal amount = null;

  @SerializedName("date")
  private String date = null;

  public Revenue type(String type) {
    this.type = type;
    return this;
  }

   /**
   * classification of revenue indicated
   * @return type
  **/
  @ApiModelProperty(example = "Room", value = "classification of revenue indicated")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Revenue currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * currency code of revenue amount indicated
   * @return currencyCode
  **/
  @ApiModelProperty(example = "USD", value = "currency code of revenue amount indicated")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public Revenue amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * rate amount
   * @return amount
  **/
  @ApiModelProperty(example = "105.55", value = "rate amount")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public Revenue date(String date) {
    this.date = date;
    return this;
  }

   /**
   * transaction date
   * @return date
  **/
  @ApiModelProperty(example = "2018-08-23", value = "transaction date")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Revenue revenue = (Revenue) o;
    return Objects.equals(this.type, revenue.type) &&
        Objects.equals(this.currencyCode, revenue.currencyCode) &&
        Objects.equals(this.amount, revenue.amount) &&
        Objects.equals(this.date, revenue.date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, currencyCode, amount, date);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Revenue {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

