/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RoomRate;
import io.swagger.client.model.TimeSpan;
import java.io.IOException;

/**
 * service info related to stay
 */
@ApiModel(description = "service info related to stay")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-26T23:47:35.032Z")
public class Service {
  @SerializedName("id")
  private String id = null;

  @SerializedName("rate")
  private RoomRate rate = null;

  @SerializedName("dates")
  private TimeSpan dates = null;

  public Service id(String id) {
    this.id = id;
    return this;
  }

   /**
   * code that identifies service
   * @return id
  **/
  @ApiModelProperty(value = "code that identifies service")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Service rate(RoomRate rate) {
    this.rate = rate;
    return this;
  }

   /**
   * Get rate
   * @return rate
  **/
  @ApiModelProperty(value = "")
  public RoomRate getRate() {
    return rate;
  }

  public void setRate(RoomRate rate) {
    this.rate = rate;
  }

  public Service dates(TimeSpan dates) {
    this.dates = dates;
    return this;
  }

   /**
   * Get dates
   * @return dates
  **/
  @ApiModelProperty(value = "")
  public TimeSpan getDates() {
    return dates;
  }

  public void setDates(TimeSpan dates) {
    this.dates = dates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Service service = (Service) o;
    return Objects.equals(this.id, service.id) &&
        Objects.equals(this.rate, service.rate) &&
        Objects.equals(this.dates, service.dates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, rate, dates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

