/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PropertyId;
import io.swagger.client.model.RoomStay;
import java.io.IOException;

/**
 * Stay
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-26T23:47:35.032Z")
public class Stay {
  @SerializedName("propertyId")
  private PropertyId propertyId = null;

  @SerializedName("reservationId")
  private String reservationId = null;

  @SerializedName("roomStay")
  private RoomStay roomStay = null;

  @SerializedName("repositoryCreated")
  private String repositoryCreated = null;

  @SerializedName("repositoryUpdated")
  private String repositoryUpdated = null;

  public Stay propertyId(PropertyId propertyId) {
    this.propertyId = propertyId;
    return this;
  }

   /**
   * Get propertyId
   * @return propertyId
  **/
  @ApiModelProperty(value = "")
  public PropertyId getPropertyId() {
    return propertyId;
  }

  public void setPropertyId(PropertyId propertyId) {
    this.propertyId = propertyId;
  }

  public Stay reservationId(String reservationId) {
    this.reservationId = reservationId;
    return this;
  }

   /**
   * id of reservation associated with stay
   * @return reservationId
  **/
  @ApiModelProperty(example = "542154", value = "id of reservation associated with stay")
  public String getReservationId() {
    return reservationId;
  }

  public void setReservationId(String reservationId) {
    this.reservationId = reservationId;
  }

  public Stay roomStay(RoomStay roomStay) {
    this.roomStay = roomStay;
    return this;
  }

   /**
   * Get roomStay
   * @return roomStay
  **/
  @ApiModelProperty(value = "")
  public RoomStay getRoomStay() {
    return roomStay;
  }

  public void setRoomStay(RoomStay roomStay) {
    this.roomStay = roomStay;
  }

  public Stay repositoryCreated(String repositoryCreated) {
    this.repositoryCreated = repositoryCreated;
    return this;
  }

   /**
   * repository create date in YYYY-MM-DDThh:mm:ss.sss format
   * @return repositoryCreated
  **/
  @ApiModelProperty(example = "2018-06-01T15:34:54.000", value = "repository create date in YYYY-MM-DDThh:mm:ss.sss format")
  public String getRepositoryCreated() {
    return repositoryCreated;
  }

  public void setRepositoryCreated(String repositoryCreated) {
    this.repositoryCreated = repositoryCreated;
  }

  public Stay repositoryUpdated(String repositoryUpdated) {
    this.repositoryUpdated = repositoryUpdated;
    return this;
  }

   /**
   * repository update date in YYYY-MM-DDThh:mm:ss.sss format
   * @return repositoryUpdated
  **/
  @ApiModelProperty(example = "2018-06-01T15:34:54.000", value = "repository update date in YYYY-MM-DDThh:mm:ss.sss format")
  public String getRepositoryUpdated() {
    return repositoryUpdated;
  }

  public void setRepositoryUpdated(String repositoryUpdated) {
    this.repositoryUpdated = repositoryUpdated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Stay stay = (Stay) o;
    return Objects.equals(this.propertyId, stay.propertyId) &&
        Objects.equals(this.reservationId, stay.reservationId) &&
        Objects.equals(this.roomStay, stay.roomStay) &&
        Objects.equals(this.repositoryCreated, stay.repositoryCreated) &&
        Objects.equals(this.repositoryUpdated, stay.repositoryUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyId, reservationId, roomStay, repositoryCreated, repositoryUpdated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Stay {\n");
    
    sb.append("    propertyId: ").append(toIndentedString(propertyId)).append("\n");
    sb.append("    reservationId: ").append(toIndentedString(reservationId)).append("\n");
    sb.append("    roomStay: ").append(toIndentedString(roomStay)).append("\n");
    sb.append("    repositoryCreated: ").append(toIndentedString(repositoryCreated)).append("\n");
    sb.append("    repositoryUpdated: ").append(toIndentedString(repositoryUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

